// <auto-generated />
using System;
using System.Net;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SeoIntelligence.Infrastructure.Persistence;

#nullable disable

namespace SeoIntelligence.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SeoIntelligenceDbContext))]
    [Migration("20260531090203_InitialMvpSchema")]
    partial class InitialMvpSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SeoIntelligence.Infrastructure.Persistence.Entities.ApiContractScopeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ApiKeyLimit")
                        .HasColumnType("integer")
                        .HasColumnName("api_key_limit");

                    b.Property<DateTime>("ConfirmedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("confirmed_at");

                    b.Property<string>("ConfirmedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("confirmed_by");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("DataUsageScope")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("data_usage_scope");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date")
                        .HasColumnName("effective_to");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("plan_name");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("ScopeKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scope_key");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("ScopeKey")
                        .IsUnique()
                        .HasDatabaseName("ux_api_contract_scopes_scope_key");

                    b.HasIndex("EffectiveFrom", "EffectiveTo")
                        .HasDatabaseName("ix_api_contract_scopes_effective_from_effective_to");

                    b.HasIndex("WorkspaceId", "Provider", "Status")
                        .HasDatabaseName("ix_api_contract_scopes_workspace_id_provider_status");

                    b.ToTable("api_contract_scopes", null, t =>
                        {
                            t.HasCheckConstraint("ck_api_contract_scopes_status", "status IN ('active', 'archived')");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("018f3f12-0002-7000-8000-000000000001"),
                            ApiKeyLimit = 5,
                            ConfirmedAt = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            ConfirmedBy = "developer",
                            CreatedAt = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataUsageScope = "internal",
                            EffectiveFrom = new DateOnly(2026, 5, 30),
                            PlanName = "standard",
                            Provider = "rakko_keyword",
                            ScopeKey = "rakko_keyword:standard:internal:2026-05-30",
                            Status = "active",
                            WorkspaceId = new Guid("018f3f12-0001-7000-8000-000000000001")
                        });
                });

            modelBuilder.Entity("SeoIntelligence.Infrastructure.Persistence.Entities.ApiCredentialEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DisabledAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("disabled_at");

                    b.Property<string>("KeyRef")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key_ref");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "Provider", "Status")
                        .HasDatabaseName("ix_api_credentials_workspace_id_provider_status");

                    b.ToTable("api_credentials", null, t =>
                        {
                            t.HasCheckConstraint("ck_api_credentials_status", "status IN ('active', 'disabled')");
                        });
                });

            modelBuilder.Entity("SeoIntelligence.Infrastructure.Persistence.Entities.AuditLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor");

                    b.Property<string>("BeforeAfterJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("before_after_json");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<IPAddress>("IpAddress")
                        .HasColumnType("inet")
                        .HasColumnName("ip_address");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("resource_type");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("Actor")
                        .HasDatabaseName("ix_audit_logs_actor");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_audit_logs_correlation_id");

                    b.HasIndex("ResourceType", "ResourceId")
                        .HasDatabaseName("ix_audit_logs_resource_type_resource_id");

                    b.HasIndex("WorkspaceId", "CreatedAt")
                        .HasDatabaseName("ix_audit_logs_workspace_id_created_at");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("SeoIntelligence.Infrastructure.Persistence.Entities.DataExportEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("ExportType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("export_type");

                    b.Property<string>("FileUri")
                        .HasColumnType("text")
                        .HasColumnName("file_uri");

                    b.Property<string>("FilterJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("filter_json");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("format");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("requested_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_data_exports_status_created_at");

                    b.HasIndex("WorkspaceId", "ProjectId", "CreatedAt")
                        .HasDatabaseName("ix_data_exports_workspace_id_project_id_created_at");

                    b.ToTable("data_exports", null, t =>
                        {
                            t.HasCheckConstraint("ck_data_exports_status", "status IN ('queued', 'running', 'waiting_external', 'succeeded', 'failed_retryable', 'failed_fatal', 'canceled')");
                        });
                });

            modelBuilder.Entity("SeoIntelligence.Infrastructure.Persistence.Entities.ExternalApiCallEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor");

                    b.Property<Guid?>("ApiContractScopeId")
                        .HasColumnType("uuid")
                        .HasColumnName("api_contract_scope_id");

                    b.Property<Guid?>("ApiCredentialId")
                        .HasColumnType("uuid")
                        .HasColumnName("api_credential_id");

                    b.Property<bool>("CacheHit")
                        .HasColumnType("boolean")
                        .HasColumnName("cache_hit");

                    b.Property<decimal>("ConsumedCredit")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("consumed_credit");

                    b.Property<string>("ContractScopeKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contract_scope_key");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("endpoint");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("text")
                        .HasColumnName("error_code");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("request_hash");

                    b.Property<string>("RequestUri")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("request_uri");

                    b.Property<string>("ResponseHash")
                        .HasColumnType("text")
                        .HasColumnName("response_hash");

                    b.Property<string>("ResponseUri")
                        .HasColumnType("text")
                        .HasColumnName("response_uri");

                    b.Property<DateTime>("RetainedUntil")
                        .HasColumnType("timestamptz")
                        .HasColumnName("retained_until");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("ApiContractScopeId");

                    b.HasIndex("ApiCredentialId");

                    b.HasIndex("ContractScopeKey")
                        .HasDatabaseName("ix_external_api_calls_contract_scope_key");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_external_api_calls_correlation_id");

                    b.HasIndex("JobId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ResponseHash")
                        .HasDatabaseName("ix_external_api_calls_response_hash");

                    b.HasIndex("StatusCode")
                        .HasDatabaseName("ix_external_api_calls_status_code");

                    b.HasIndex("WorkspaceId");

                    b.HasIndex("Provider", "Endpoint", "CreatedAt")
                        .HasDatabaseName("ix_external_api_calls_provider_endpoint_created_at");

                    b.ToTable("external_api_calls", (string)null);
                });

            modelBuilder.Entity("SeoIntelligence.Infrastructure.Persistence.Entities.JobEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("error_json");

                    b.Property<string>("IdempotencyKey")
                        .HasColumnType("text")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("job_type");

                    b.Property<DateTime?>("NextRunAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("next_run_at");

                    b.Property<int>("Progress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("progress");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("RequestHash")
                        .HasColumnType("text")
                        .HasColumnName("request_hash");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("requested_by");

                    b.Property<Guid?>("ResultResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("result_resource_id");

                    b.Property<string>("ResultResourceType")
                        .HasColumnType("text")
                        .HasColumnName("result_resource_type");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("Status", "NextRunAt")
                        .HasDatabaseName("ix_jobs_status_next_run_at");

                    b.HasIndex("WorkspaceId", "ProjectId", "CreatedAt")
                        .HasDatabaseName("ix_jobs_workspace_id_project_id_created_at");

                    b.ToTable("jobs", null, t =>
                        {
                            t.HasCheckConstraint("ck_jobs_progress", "progress >= 0 AND progress <= 100");

                            t.HasCheckConstraint("ck_jobs_status", "status IN ('queued', 'running', 'waiting_external', 'succeeded', 'failed_retryable', 'failed_fatal', 'canceled')");
                        });
                });

            modelBuilder.Entity("SeoIntelligence.Infrastructure.Persistence.Entities.JobExternalRequestEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completed_at");

                    b.Property<decimal>("ConsumedCredit")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("consumed_credit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("endpoint");

                    b.Property<string>("ErrorJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("error_json");

                    b.Property<string>("ExternalRequestId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_request_id");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_no");

                    b.Property<Guid?>("SourceCallId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_call_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ExternalRequestId")
                        .HasDatabaseName("ix_job_external_requests_external_request_id");

                    b.HasIndex("SourceCallId");

                    b.HasIndex("JobId", "SequenceNo")
                        .HasDatabaseName("ix_job_external_requests_job_id_sequence_no");

                    b.HasIndex("Status", "UpdatedAt")
                        .HasDatabaseName("ix_job_external_requests_status_updated_at");

                    b.ToTable("job_external_requests", (string)null);
                });

            modelBuilder.Entity("SeoIntelligence.Infrastructure.Persistence.Entities.KeywordEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<string>("NormalizedText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_text");

                    b.Property<string>("TextHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text_hash");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedText")
                        .HasDatabaseName("ix_keywords_normalized_text_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("NormalizedText"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("NormalizedText"), new[] { "gin_trgm_ops" });

                    b.HasIndex("Language", "TextHash")
                        .IsUnique()
                        .HasDatabaseName("ux_keywords_language_text_hash");

                    b.ToTable("keywords", (string)null);
                });

            modelBuilder.Entity("SeoIntelligence.Infrastructure.Persistence.Entities.KeywordMetricEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Competition")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)")
                        .HasColumnName("competition");

                    b.Property<string>("ContractScopeKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contract_scope_key");

                    b.Property<decimal>("Cpc")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("cpc");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("fetched_at");

                    b.Property<string>("FirstSeenRange")
                        .HasColumnType("text")
                        .HasColumnName("first_seen_range");

                    b.Property<Guid>("KeywordId")
                        .HasColumnType("uuid")
                        .HasColumnName("keyword_id");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<int>("SearchVolume")
                        .HasColumnType("integer")
                        .HasColumnName("search_volume");

                    b.Property<decimal>("SeoDifficulty")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)")
                        .HasColumnName("seo_difficulty");

                    b.Property<Guid?>("SourceCallId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_call_id");

                    b.HasKey("Id");

                    b.HasIndex("SourceCallId")
                        .HasDatabaseName("ix_keyword_metrics_source_call_id");

                    b.HasIndex("KeywordId", "Location", "Language", "ContractScopeKey", "FetchedAt")
                        .IsDescending(false, false, false, false, true)
                        .HasDatabaseName("ix_keyword_metrics_keyword_id_location_language_contract_scope_key_fetched_at");

                    b.ToTable("keyword_metrics", (string)null);
                });

            modelBuilder.Entity("SeoIntelligence.Infrastructure.Persistence.Entities.KeywordMonthlyVolumeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContractScopeKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contract_scope_key");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("fetched_at");

                    b.Property<Guid>("KeywordId")
                        .HasColumnType("uuid")
                        .HasColumnName("keyword_id");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<int>("SearchVolume")
                        .HasColumnType("integer")
                        .HasColumnName("search_volume");

                    b.Property<Guid?>("SourceCallId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_call_id");

                    b.Property<string>("YearMonth")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("char(7)")
                        .HasColumnName("year_month");

                    b.HasKey("Id");

                    b.HasIndex("SourceCallId")
                        .HasDatabaseName("ix_keyword_monthly_volumes_source_call_id");

                    b.HasIndex("KeywordId", "Location", "Language", "ContractScopeKey", "YearMonth", "FetchedAt")
                        .IsDescending(false, false, false, false, false, true)
                        .HasDatabaseName("ix_keyword_monthly_volumes_keyword_location_language_scope_month_fetched_at");

                    b.ToTable("keyword_monthly_volumes", (string)null);
                });

            modelBuilder.Entity("SeoIntelligence.Infrastructure.Persistence.Entities.KeywordSeedEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Memo")
                        .HasColumnType("text")
                        .HasColumnName("memo");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Seed")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("seed");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_keyword_seeds_project_id");

                    b.ToTable("keyword_seeds", (string)null);
                });

            modelBuilder.Entity("SeoIntelligence.Infrastructure.Persistence.Entities.KeywordSuggestionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("engine");

                    b.Property<int>("EngineCount")
                        .HasColumnType("integer")
                        .HasColumnName("engine_count");

                    b.Property<string>("FirstSeenRange")
                        .HasColumnType("text")
                        .HasColumnName("first_seen_range");

                    b.Property<Guid>("KeywordId")
                        .HasColumnType("uuid")
                        .HasColumnName("keyword_id");

                    b.Property<Guid>("SeedId")
                        .HasColumnType("uuid")
                        .HasColumnName("seed_id");

                    b.Property<string>("SuggestClass")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("suggest_class");

                    b.HasKey("Id");

                    b.HasIndex("KeywordId")
                        .HasDatabaseName("ix_keyword_suggestions_keyword_id");

                    b.HasIndex("SeedId")
                        .HasDatabaseName("ix_keyword_suggestions_seed_id");

                    b.ToTable("keyword_suggestions", (string)null);
                });

            modelBuilder.Entity("SeoIntelligence.Infrastructure.Persistence.Entities.LanguageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language_code");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language_name");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("synced_at");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_languages_status");

                    b.HasIndex("Provider", "LanguageCode")
                        .IsUnique()
                        .HasDatabaseName("ux_languages_provider_language_code");

                    b.ToTable("languages", (string)null);
                });

            modelBuilder.Entity("SeoIntelligence.Infrastructure.Persistence.Entities.LocationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("country_code");

                    b.Property<string>("LocationCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location_code");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location_name");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("synced_at");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_locations_status");

                    b.HasIndex("Provider", "LocationCode")
                        .IsUnique()
                        .HasDatabaseName("ux_locations_provider_location_code");

                    b.ToTable("locations", (string)null);
                });

            modelBuilder.Entity("SeoIntelligence.Infrastructure.Persistence.Entities.LsiPaaItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<decimal>("Importance")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)")
                        .HasColumnName("importance");

                    b.Property<Guid?>("KeywordId")
                        .HasColumnType("uuid")
                        .HasColumnName("keyword_id");

                    b.Property<string>("QuestionText")
                        .HasColumnType("text")
                        .HasColumnName("question_text");

                    b.Property<Guid>("SeedKeywordId")
                        .HasColumnType("uuid")
                        .HasColumnName("seed_keyword_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("KeywordId")
                        .HasDatabaseName("ix_lsi_paa_items_keyword_id");

                    b.HasIndex("SeedKeywordId")
                        .HasDatabaseName("ix_lsi_paa_items_seed_keyword_id");

                    b.ToTable("lsi_paa_items", (string)null);
                });

            modelBuilder.Entity("SeoIntelligence.Infrastructure.Persistence.Entities.NotificationChannelEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChannelType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DisabledAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("disabled_at");

                    b.Property<string>("EventTypesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("event_types_json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<string>("WebhookSecretRef")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("webhook_secret_ref");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("ChannelType")
                        .HasDatabaseName("ix_notification_channels_channel_type");

                    b.HasIndex("ProjectId");

                    b.HasIndex("WorkspaceId", "ProjectId", "Status")
                        .HasDatabaseName("ix_notification_channels_workspace_id_project_id_status");

                    b.ToTable("notification_channels", null, t =>
                        {
                            t.HasCheckConstraint("ck_notification_channels_status", "status IN ('active', 'disabled')");
                        });
                });

            modelBuilder.Entity("SeoIntelligence.Infrastructure.Persistence.Entities.NotificationDeliveryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid")
                        .HasColumnName("channel_id");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("delivered_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("next_retry_at");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload_hash");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("ResourceId")
                        .HasColumnType("text")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceType")
                        .HasColumnType("text")
                        .HasColumnName("resource_type");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_notification_deliveries_correlation_id");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_notification_deliveries_job_id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ResourceType", "ResourceId")
                        .HasDatabaseName("ix_notification_deliveries_resource_type_resource_id");

                    b.HasIndex("Status", "NextRetryAt")
                        .HasDatabaseName("ix_notification_deliveries_status_next_retry_at");

                    b.HasIndex("WorkspaceId", "ProjectId", "CreatedAt")
                        .HasDatabaseName("ix_notification_deliveries_workspace_id_project_id_created_at");

                    b.ToTable("notification_deliveries", null, t =>
                        {
                            t.HasCheckConstraint("ck_notification_deliveries_status", "status IN ('pending', 'retrying', 'succeeded', 'failed')");
                        });
                });

            modelBuilder.Entity("SeoIntelligence.Infrastructure.Persistence.Entities.ProjectEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("archived_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultLanguage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("default_language");

                    b.Property<string>("DefaultLocation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("default_location");

                    b.Property<string>("KpiJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("kpi_json");

                    b.Property<string>("Memo")
                        .HasColumnType("text")
                        .HasColumnName("memo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_projects_workspace_id_name");

                    b.HasIndex("WorkspaceId", "Status")
                        .HasDatabaseName("ix_projects_workspace_id_status");

                    b.ToTable("projects", null, t =>
                        {
                            t.HasCheckConstraint("ck_projects_status", "status IN ('active', 'archived')");
                        });
                });

            modelBuilder.Entity("SeoIntelligence.Infrastructure.Persistence.Entities.ProjectKeywordScoreEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("KeywordId")
                        .HasColumnType("uuid")
                        .HasColumnName("keyword_id");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<decimal>("OpportunityScore")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)")
                        .HasColumnName("opportunity_score");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("ScoreComponentsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("score_components_json");

                    b.Property<DateTime>("ScoredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("scored_at");

                    b.Property<Guid?>("SourceCallId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_call_id");

                    b.HasKey("Id");

                    b.HasIndex("KeywordId");

                    b.HasIndex("SourceCallId")
                        .HasDatabaseName("ix_project_keyword_scores_source_call_id");

                    b.HasIndex("ProjectId", "OpportunityScore")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_project_keyword_scores_project_id_opportunity_score");

                    b.HasIndex("ProjectId", "KeywordId", "Location", "Language")
                        .IsUnique()
                        .HasDatabaseName("ux_project_keyword_scores_project_id_keyword_id_location_language");

                    b.ToTable("project_keyword_scores", (string)null);
                });

            modelBuilder.Entity("SeoIntelligence.Infrastructure.Persistence.Entities.QuestionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<decimal>("Importance")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)")
                        .HasColumnName("importance");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_text");

                    b.Property<Guid?>("SeedKeywordId")
                        .HasColumnType("uuid")
                        .HasColumnName("seed_keyword_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_questions_project_id");

                    b.HasIndex("SeedKeywordId")
                        .HasDatabaseName("ix_questions_seed_keyword_id");

                    b.ToTable("questions", (string)null);
                });

            modelBuilder.Entity("SeoIntelligence.Infrastructure.Persistence.Entities.RankingKeywordEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("KeywordId")
                        .HasColumnType("uuid")
                        .HasColumnName("keyword_id");

                    b.Property<string>("MetricsSnapshotJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metrics_snapshot_json");

                    b.Property<decimal>("Relevance")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)")
                        .HasColumnName("relevance");

                    b.Property<Guid>("SeedKeywordId")
                        .HasColumnType("uuid")
                        .HasColumnName("seed_keyword_id");

                    b.Property<int>("WordCount")
                        .HasColumnType("integer")
                        .HasColumnName("word_count");

                    b.HasKey("Id");

                    b.HasIndex("KeywordId")
                        .HasDatabaseName("ix_ranking_keywords_keyword_id");

                    b.HasIndex("SeedKeywordId")
                        .HasDatabaseName("ix_ranking_keywords_seed_keyword_id");

                    b.ToTable("ranking_keywords", (string)null);
                });

            modelBuilder.Entity("SeoIntelligence.Infrastructure.Persistence.Entities.RelatedKeywordEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("KeywordId")
                        .HasColumnType("uuid")
                        .HasColumnName("keyword_id");

                    b.Property<string>("MatchType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("match_type");

                    b.Property<string>("MetricsSnapshotJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metrics_snapshot_json");

                    b.Property<Guid>("SeedId")
                        .HasColumnType("uuid")
                        .HasColumnName("seed_id");

                    b.HasKey("Id");

                    b.HasIndex("KeywordId")
                        .HasDatabaseName("ix_related_keywords_keyword_id");

                    b.HasIndex("SeedId")
                        .HasDatabaseName("ix_related_keywords_seed_id");

                    b.ToTable("related_keywords", (string)null);
                });

            modelBuilder.Entity("SeoIntelligence.Infrastructure.Persistence.Entities.SearchVolumeJobEntity", b =>
                {
                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<int>("AggregationMonths")
                        .HasColumnType("integer")
                        .HasColumnName("aggregation_months");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("RequestOptionsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("request_options_json");

                    b.Property<string>("StatusJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("status_json");

                    b.HasKey("JobId");

                    b.ToTable("search_volume_jobs", (string)null);
                });

            modelBuilder.Entity("SeoIntelligence.Infrastructure.Persistence.Entities.SearchVolumeResultEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("CacheHit")
                        .HasColumnType("boolean")
                        .HasColumnName("cache_hit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("data_source");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<Guid>("KeywordId")
                        .HasColumnType("uuid")
                        .HasColumnName("keyword_id");

                    b.Property<string>("MetricsSnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metrics_snapshot_json");

                    b.Property<Guid?>("SourceCallId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_call_id");

                    b.Property<string>("TrendsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("trends_json");

                    b.HasKey("Id");

                    b.HasIndex("CacheHit")
                        .HasDatabaseName("ix_search_volume_results_cache_hit");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_search_volume_results_job_id");

                    b.HasIndex("KeywordId")
                        .HasDatabaseName("ix_search_volume_results_keyword_id");

                    b.HasIndex("SourceCallId");

                    b.ToTable("search_volume_results", (string)null);
                });

            modelBuilder.Entity("SeoIntelligence.Infrastructure.Persistence.Entities.SiteEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("archived_at");

                    b.Property<string>("CanonicalUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("canonical_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("domain");

                    b.Property<string>("Memo")
                        .HasColumnType("text")
                        .HasColumnName("memo");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Domain")
                        .HasDatabaseName("ix_sites_domain");

                    b.HasIndex("ProjectId", "Status")
                        .HasDatabaseName("ix_sites_project_id_status");

                    b.ToTable("sites", null, t =>
                        {
                            t.HasCheckConstraint("ck_sites_status", "status IN ('active', 'archived')");
                        });
                });

            modelBuilder.Entity("SeoIntelligence.Infrastructure.Persistence.Entities.WorkspaceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultLanguage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("default_language");

                    b.Property<string>("DefaultLocation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("default_location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NotificationDefaultsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("notification_defaults_json");

                    b.Property<string>("RetentionSettingsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("retention_settings_json");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_workspaces_name");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_workspaces_status");

                    b.ToTable("workspaces", null, t =>
                        {
                            t.HasCheckConstraint("ck_workspaces_status", "status IN ('active')");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("018f3f12-0001-7000-8000-000000000001"),
                            CreatedAt = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultLanguage = "ja",
                            DefaultLocation = "JP",
                            Name = "Default Workspace",
                            NotificationDefaultsJson = "{\"discordEnabled\":false}",
                            RetentionSettingsJson = "{\"externalApiRawDataMonths\":24,\"processedDataMonths\":24,\"auditLogMonths\":36}",
                            Status = "active",
                            UpdatedAt = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("SeoIntelligence.Infrastructure.Persistence.Entities.ApiContractScopeEntity", b =>
                {
                    b.HasOne("SeoIntelligence.Infrastructure.Persistence.Entities.WorkspaceEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SeoIntelligence.Infrastructure.Persistence.Entities.ApiCredentialEntity", b =>
                {
                    b.HasOne("SeoIntelligence.Infrastructure.Persistence.Entities.WorkspaceEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SeoIntelligence.Infrastructure.Persistence.Entities.AuditLogEntity", b =>
                {
                    b.HasOne("SeoIntelligence.Infrastructure.Persistence.Entities.WorkspaceEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SeoIntelligence.Infrastructure.Persistence.Entities.DataExportEntity", b =>
                {
                    b.HasOne("SeoIntelligence.Infrastructure.Persistence.Entities.ProjectEntity", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SeoIntelligence.Infrastructure.Persistence.Entities.WorkspaceEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SeoIntelligence.Infrastructure.Persistence.Entities.ExternalApiCallEntity", b =>
                {
                    b.HasOne("SeoIntelligence.Infrastructure.Persistence.Entities.ApiContractScopeEntity", null)
                        .WithMany()
                        .HasForeignKey("ApiContractScopeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SeoIntelligence.Infrastructure.Persistence.Entities.ApiCredentialEntity", null)
                        .WithMany()
                        .HasForeignKey("ApiCredentialId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SeoIntelligence.Infrastructure.Persistence.Entities.JobEntity", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SeoIntelligence.Infrastructure.Persistence.Entities.ProjectEntity", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SeoIntelligence.Infrastructure.Persistence.Entities.WorkspaceEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SeoIntelligence.Infrastructure.Persistence.Entities.JobEntity", b =>
                {
                    b.HasOne("SeoIntelligence.Infrastructure.Persistence.Entities.ProjectEntity", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SeoIntelligence.Infrastructure.Persistence.Entities.WorkspaceEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SeoIntelligence.Infrastructure.Persistence.Entities.JobExternalRequestEntity", b =>
                {
                    b.HasOne("SeoIntelligence.Infrastructure.Persistence.Entities.JobEntity", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SeoIntelligence.Infrastructure.Persistence.Entities.ExternalApiCallEntity", null)
                        .WithMany()
                        .HasForeignKey("SourceCallId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SeoIntelligence.Infrastructure.Persistence.Entities.KeywordMetricEntity", b =>
                {
                    b.HasOne("SeoIntelligence.Infrastructure.Persistence.Entities.KeywordEntity", null)
                        .WithMany()
                        .HasForeignKey("KeywordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SeoIntelligence.Infrastructure.Persistence.Entities.ExternalApiCallEntity", null)
                        .WithMany()
                        .HasForeignKey("SourceCallId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SeoIntelligence.Infrastructure.Persistence.Entities.KeywordMonthlyVolumeEntity", b =>
                {
                    b.HasOne("SeoIntelligence.Infrastructure.Persistence.Entities.KeywordEntity", null)
                        .WithMany()
                        .HasForeignKey("KeywordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SeoIntelligence.Infrastructure.Persistence.Entities.ExternalApiCallEntity", null)
                        .WithMany()
                        .HasForeignKey("SourceCallId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SeoIntelligence.Infrastructure.Persistence.Entities.KeywordSeedEntity", b =>
                {
                    b.HasOne("SeoIntelligence.Infrastructure.Persistence.Entities.ProjectEntity", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SeoIntelligence.Infrastructure.Persistence.Entities.KeywordSuggestionEntity", b =>
                {
                    b.HasOne("SeoIntelligence.Infrastructure.Persistence.Entities.KeywordEntity", null)
                        .WithMany()
                        .HasForeignKey("KeywordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SeoIntelligence.Infrastructure.Persistence.Entities.KeywordSeedEntity", null)
                        .WithMany()
                        .HasForeignKey("SeedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SeoIntelligence.Infrastructure.Persistence.Entities.LsiPaaItemEntity", b =>
                {
                    b.HasOne("SeoIntelligence.Infrastructure.Persistence.Entities.KeywordEntity", null)
                        .WithMany()
                        .HasForeignKey("KeywordId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SeoIntelligence.Infrastructure.Persistence.Entities.KeywordEntity", null)
                        .WithMany()
                        .HasForeignKey("SeedKeywordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SeoIntelligence.Infrastructure.Persistence.Entities.NotificationChannelEntity", b =>
                {
                    b.HasOne("SeoIntelligence.Infrastructure.Persistence.Entities.ProjectEntity", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SeoIntelligence.Infrastructure.Persistence.Entities.WorkspaceEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SeoIntelligence.Infrastructure.Persistence.Entities.NotificationDeliveryEntity", b =>
                {
                    b.HasOne("SeoIntelligence.Infrastructure.Persistence.Entities.NotificationChannelEntity", null)
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SeoIntelligence.Infrastructure.Persistence.Entities.JobEntity", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SeoIntelligence.Infrastructure.Persistence.Entities.ProjectEntity", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SeoIntelligence.Infrastructure.Persistence.Entities.WorkspaceEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SeoIntelligence.Infrastructure.Persistence.Entities.ProjectEntity", b =>
                {
                    b.HasOne("SeoIntelligence.Infrastructure.Persistence.Entities.WorkspaceEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SeoIntelligence.Infrastructure.Persistence.Entities.ProjectKeywordScoreEntity", b =>
                {
                    b.HasOne("SeoIntelligence.Infrastructure.Persistence.Entities.KeywordEntity", null)
                        .WithMany()
                        .HasForeignKey("KeywordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SeoIntelligence.Infrastructure.Persistence.Entities.ProjectEntity", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SeoIntelligence.Infrastructure.Persistence.Entities.ExternalApiCallEntity", null)
                        .WithMany()
                        .HasForeignKey("SourceCallId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SeoIntelligence.Infrastructure.Persistence.Entities.QuestionEntity", b =>
                {
                    b.HasOne("SeoIntelligence.Infrastructure.Persistence.Entities.ProjectEntity", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SeoIntelligence.Infrastructure.Persistence.Entities.KeywordEntity", null)
                        .WithMany()
                        .HasForeignKey("SeedKeywordId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SeoIntelligence.Infrastructure.Persistence.Entities.RankingKeywordEntity", b =>
                {
                    b.HasOne("SeoIntelligence.Infrastructure.Persistence.Entities.KeywordEntity", null)
                        .WithMany()
                        .HasForeignKey("KeywordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SeoIntelligence.Infrastructure.Persistence.Entities.KeywordEntity", null)
                        .WithMany()
                        .HasForeignKey("SeedKeywordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SeoIntelligence.Infrastructure.Persistence.Entities.RelatedKeywordEntity", b =>
                {
                    b.HasOne("SeoIntelligence.Infrastructure.Persistence.Entities.KeywordEntity", null)
                        .WithMany()
                        .HasForeignKey("KeywordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SeoIntelligence.Infrastructure.Persistence.Entities.KeywordSeedEntity", null)
                        .WithMany()
                        .HasForeignKey("SeedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SeoIntelligence.Infrastructure.Persistence.Entities.SearchVolumeJobEntity", b =>
                {
                    b.HasOne("SeoIntelligence.Infrastructure.Persistence.Entities.JobEntity", null)
                        .WithOne()
                        .HasForeignKey("SeoIntelligence.Infrastructure.Persistence.Entities.SearchVolumeJobEntity", "JobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SeoIntelligence.Infrastructure.Persistence.Entities.SearchVolumeResultEntity", b =>
                {
                    b.HasOne("SeoIntelligence.Infrastructure.Persistence.Entities.JobEntity", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SeoIntelligence.Infrastructure.Persistence.Entities.KeywordEntity", null)
                        .WithMany()
                        .HasForeignKey("KeywordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SeoIntelligence.Infrastructure.Persistence.Entities.ExternalApiCallEntity", null)
                        .WithMany()
                        .HasForeignKey("SourceCallId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SeoIntelligence.Infrastructure.Persistence.Entities.SiteEntity", b =>
                {
                    b.HasOne("SeoIntelligence.Infrastructure.Persistence.Entities.ProjectEntity", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
